const offest = 1200,
	thickWidth = 85,
	middleWidth = 78,
	fineWidth = 43,
	offestX = 8,
	offestY = 8,
	initX = 3*thickWidth + 7*middleWidth + 9*fineWidth + offest - 33*offestX + thickWidth,
	initY = offest + 102*offestY,
	plane = 12,
	depthOffest = 0,
	durationVal = .2,
	delayVal = 1,
	part1FirstDelay = .8,
	part1LastDelay = 11.5*delayVal + part1FirstDelay + 1.5,
	part2z = 20
export const lands = [
	{
		x: initX + 3* thickWidth,
		y: initY,
		z: -thickWidth*4 - plane,
		width: 5* thickWidth,
		height: 20 * thickWidth,
		depth: 3 * thickWidth,
		animate: 0,
		visible: true,
		duration: part1FirstDelay* 2,
		delay: 0,
	},
	{
		x: initX - thickWidth,
		y: initY,
		z: -thickWidth* 2.5 - plane,
		width: thickWidth,
		height: 3 * thickWidth,
		depth: 5 * thickWidth - 2,
		animate: 1,
		duration: durationVal,
		delay: part1FirstDelay
	},
	{
		x: initX + thickWidth - 5,
		y: initY + thickWidth + 2*offestY,
		z: -thickWidth* 2.5 - plane,
		width: thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: .5*delayVal + part1FirstDelay
	},
	{
		x: initX + thickWidth + 5,
		y: initY + 2*thickWidth + 2*offestY,
		z: -thickWidth* 2.5 - plane - 1,
		width: thickWidth + 20,
		height: thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: delayVal + part1FirstDelay
	},
	{
		x: initX + 2*thickWidth + 2.4*offestY,
		y: initY + 2.5*thickWidth + 2*offestY,
		z: -thickWidth* 2.5 - plane - 1,
		width: thickWidth + 20,
		height: 2* thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 1.5*delayVal + part1FirstDelay
	},
	{ // 6
		x: initX + 2*thickWidth + 2.4*offestY,
		y: initY + 4*thickWidth + 2*offestY,
		z: -thickWidth* 2.5 - plane - 2,
		width: thickWidth + 20,
		height: thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 2*delayVal + part1FirstDelay
	},
	{
		x: initX + 3*thickWidth,
		y: initY + 4*thickWidth + 4*offestY,
		z: -thickWidth* 2.5 - plane - 2,
		width: thickWidth,
		height: 1.5*thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 2.5*delayVal + part1FirstDelay
	},
	{ // 8
		x: initX + 3.5*thickWidth,
		y: initY + 5*thickWidth,
		z: -thickWidth* 2.5 - plane - 1,
		width: thickWidth,
		height: 1.5*thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 3*delayVal + part1FirstDelay
	},
	{
		x: initX + 4*thickWidth,
		y: initY + 6*thickWidth,
		z: -thickWidth* 2.5 - plane - 2,
		width: thickWidth,
		height: 2*thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 3.5*delayVal + part1FirstDelay
	},
	{
		x: initX + 4.5*thickWidth,
		y: initY + 7*thickWidth,
		z: -thickWidth* 2.5 - plane - 2,
		width: thickWidth,
		height: 1.5*thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 4*delayVal + part1FirstDelay
	},
	{
		x: initX + 5*thickWidth,
		y: initY + 7.75*thickWidth,
		z: -thickWidth* 2.5 - plane - 2,
		width: thickWidth,
		height: 1.5*thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 4.5*delayVal + part1FirstDelay
	},
	{
		x: initX + 5.5*thickWidth,
		y: initY + 10.25*thickWidth,
		z: -thickWidth* 2.5 - plane - 2,
		width: thickWidth,
		height: 5*thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 5*delayVal + part1FirstDelay
	},
	{
		x: initX + 5.75*thickWidth,
		y: initY + 13*thickWidth,
		z: -thickWidth* 2.5 - plane - 2,
		width: 1.5*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 5.5*delayVal + part1FirstDelay
	},
	{// 14
		x: initX + 6.75*thickWidth,
		y: initY + 13.25*thickWidth,
		z: -thickWidth* 2.5 - plane - 3,
		width: thickWidth,
		height: 1.5*thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 6*delayVal + part1FirstDelay
	},
	{
		x: initX + 7*thickWidth,
		y: initY + 14*thickWidth,
		z: -thickWidth* 2.5 - plane - 3,
		width: 1.5*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 7.5*delayVal + part1FirstDelay
	},
	{
		x: initX + 8*thickWidth,
		y: initY + 14.25*thickWidth,
		z: -thickWidth* 2.5 - plane - 2,
		width: thickWidth,
		height: 1.5*thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 8*delayVal + part1FirstDelay
	},
	{
		x: initX + 8.25*thickWidth,
		y: initY + 15.25*thickWidth,
		z: -thickWidth* 2.5 - plane - 2,
		width: 1.5*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 8.5*delayVal + part1FirstDelay
	},
	{
		x: initX + 9.5*thickWidth,
		y: initY + 15.25*thickWidth,
		z: -thickWidth* 2.5 - plane - 2,
		width: thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 9*delayVal + part1FirstDelay
	},
	{
		x: initX + 10*thickWidth,
		y: initY + 16*thickWidth,
		z: -thickWidth* 2.5 - plane - 2,
		width: 1.5*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 9.5*delayVal + part1FirstDelay
	},
	{
		x: initX + 10.5*thickWidth,
		y: initY + 16.5*thickWidth,
		z: -thickWidth* 2.5 - plane - 2,
		width: 1.5*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 10*delayVal + part1FirstDelay
	},
	{
		x: initX + 12*thickWidth,
		y: initY + 17*thickWidth,
		z: -thickWidth* 2.5 - plane - 2,
		width: 3*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 10.5*delayVal + part1FirstDelay
	},
	{
		x: initX + 14.5*thickWidth,
		y: initY + 17.5*thickWidth,
		z: -thickWidth* 2.5 - plane - 2,
		width: 3*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 11*delayVal + part1FirstDelay
	},
	{
		x: initX + 16*thickWidth,
		y: initY + 18*thickWidth,
		z: -thickWidth* 2.5 - plane - 2,
		width: thickWidth,
		height: 0.5*thickWidth,
		depth: 5 * thickWidth - depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 11.5*delayVal + part1FirstDelay
	},

	//转接处
	{
		x: initX + 18*thickWidth,
		y: initY + 18*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: .5*delayVal + part1LastDelay
	},
	{
		x: initX + 18.1*thickWidth,
		y: initY + 19*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: 1.2*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: delayVal + part1LastDelay
	},
	{
		x: initX + 19.2*thickWidth,
		y: initY + 19.1*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: thickWidth,
		height: 1.2*thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 1.5*delayVal + part1LastDelay
	},
	{
		x: initX + 19.3*thickWidth,
		y: initY + 20.1*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: 1.2*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 2*delayVal + part1LastDelay
	},
	{
		x: initX + 20.4*thickWidth,
		y: initY + 20.2*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: thickWidth,
		height: 1.2*thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 2.5*delayVal + part1LastDelay
	},
	{
		x: initX + 20.7*thickWidth,
		y: initY + 21.3*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: 1.6*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 3*delayVal + part1LastDelay
	},
	{
		x: initX + 22*thickWidth,
		y: initY + 22*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: 3.2*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 3.5*delayVal + part1LastDelay
	},
	{
		x: initX + 23.1*thickWidth,
		y: initY + 22.7*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: 1.6*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 4*delayVal + part1LastDelay
	},
	{
		x: initX + 23.4*thickWidth,
		y: initY + 23.4*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: 1.6*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 4.5*delayVal + part1LastDelay
	},
	{
		x: initX + (23.4+(3.2-1.6)/2+.3)*thickWidth,
		y: initY + (24.4 - .3)*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: 3.2*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 5*delayVal + part1LastDelay
	},
	{
		x: initX + (27.7 - .7*1.6)*thickWidth,
		y: initY + (25.1 - .3)*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: 3.2*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 5.5*delayVal + part1LastDelay
	},
	{
		x: initX + (27.7 - .7*1.6 + 3.2 - .7*1.6)*thickWidth,
		y: initY + (25.1 - .3 + 1 - .3)*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: 3.2*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 6*delayVal + part1LastDelay
	},
	{
		x: initX + (27.7 - .7*1.6 + 3.2 - .7*1.6 + 3.2*.5 - .5)*thickWidth,
		y: initY + (25.1 - .3 + 1 -.3 + 1)*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 6.5*delayVal + part1LastDelay
	},
	{
		x: initX + (27.7 - .7*1.6 + 3.2 - .7*1.6 + 3.2*.5 - .5 + 1)*thickWidth,
		y: initY + (25.1 - .3 + 1 -.3 + 1 + (1.2-1)*.5)*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: thickWidth,
		height: 1.2*thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 7*delayVal + part1LastDelay
	},
	{
		x: initX + (27.7 - .7*1.6 + 3.2 - .7*1.6 + 3.2*.5 - .5 + 1 + .1)*thickWidth,
		y: initY + (25.1 - .3 + 1 -.3 + 1 + (1.2-1)*.5 + 1 + .1)*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: 1.2*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 7.5*delayVal + part1LastDelay
	},
	{
		x: initX + (27.7 - .7*1.6 + 3.2 - .7*1.6 + 3.2*.5 - .5 + 1 + .1 + 1 + .1)*thickWidth,
		y: initY + (25.1 - .3 + 1 -.3 + 1 + (1.2-1)*.5 + 1 + .1 + .1)*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: thickWidth,
		height: 1.2*thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 8*delayVal + part1LastDelay
	},
	{
		x: initX + (27.7 - .7*1.6 + 3.2 - .7*1.6 + 3.2*.5 - .5 + 1 + .1 + 1 + .1 + .1)*thickWidth,
		y: initY + (25.1 - .3 + 1 -.3 + 1 + (1.2-1)*.5 + 1 + .1 + .1 + 1 + .1)*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: 1.2*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 8.5*delayVal + part1LastDelay
	},
	{
		x: initX + (27.7 - .7*1.6 + 3.2 - .7*1.6 + 3.2*.5 - .5 + 1 + .1 + 1 + .1 + .1 + 1 + .1)*thickWidth,
		y: initY + (25.1 - .3 + 1 -.3 + 1 + (1.2-1)*.5 + 1 + .1 + .1 + 1 + .1 + .4)*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: thickWidth,
		height: 1.8*thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 9*delayVal + part1LastDelay
	},
	{
		x: initX + (27.7 - .7*1.6 + 3.2 - .7*1.6 + 3.2*.5 - .5 + 1 + .1 + 1 + .1 + .1 + 1 + .1 + .4)*thickWidth,
		y: initY + (25.1 - .3 + 1 -.3 + 1 + (1.2-1)*.5 + 1 + .1 + .1 + 1 + .1 + .4 + 1 + .4)*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: 1.8*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 9.5*delayVal + part1LastDelay
	},
	{
		x: initX + (27.7 - .7*1.6 + 3.2 - .7*1.6 + 3.2*.5 - .5 + 1 + .1 + 1 + .1 + .1 + 1 + .1 + .4 + 1.8*.5)*thickWidth,
		y: initY + (25.1 - .3 + 1 -.3 + 1 + (1.2-1)*.5 + 1 + .1 + .1 + 1 + .1 + .4 + 1 + .4 + 1 - .2)*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: 1.8*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 10*delayVal + part1LastDelay
	},
	{
		x: initX + (27.7 - .7*1.6 + 3.2 - .7*1.6 + 3.2*.5 - .5 + 1 + .1 + 1 + .1 + .1 + 1 + .1 + .4 + (1.8*.5)*2)*thickWidth,
		y: initY + (25.1 - .3 + 1 -.3 + 1 + (1.2-1)*.5 + 1 + .1 + .1 + 1 + .1 + .4 + 1 + .4 + 1 - .2 + 1 - .2)*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: 1.8*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 10.5*delayVal + part1LastDelay
	},
	{
		x: initX + (27.7 - .7*1.6 + 3.2 - .7*1.6 + 3.2*.5 - .5 + 1 + .1 + 1 + .1 + .1 + 1 + .1 + .4 + (1.8*.5)*2 + 1.8*.5 - .5)*thickWidth,
		y: initY + (25.1 - .3 + 1 -.3 + 1 + (1.2-1)*.5 + 1 + .1 + .1 + 1 + .1 + .4 + 1 + .4 + 1 - .2 + 1 - .2 + 1.1 +.5)*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: thickWidth,
		height: 2.2*thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 11*delayVal + part1LastDelay
	},
	{
		x: initX + (27.7 - .7*1.6 + 3.2 - .7*1.6 + 3.2*.5 - .5 + 1 + .1 + 1 + .1 + .1 + 1 + .1 + .4 + (1.8*.5)*2 + 1.8*.5 - .5 + (1.4-1)*.5)*thickWidth,
		y: initY + (25.1 - .3 + 1 -.3 + 1 + (1.2-1)*.5 + 1 + .1 + .1 + 1 + .1 + .4 + 1 + .4 + 1 - .2 + 1 - .2 + 1.1 +.5 + 2.2*.5 + .5)*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: 1.4*thickWidth,
		height: thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 11.5*delayVal + part1LastDelay
	},
	{
		x: initX + (27.7 - .7*1.6 + 3.2 - .7*1.6 + 3.2*.5 - .5 + 1 + .1 + 1 + .1 + .1 + 1 + .1 + .4 + (1.8*.5)*2 + 1.8*.5 - .5 + (1.4-1)*.5 + .5)*thickWidth,
		y: initY + (25.1 - .3 + 1 -.3 + 1 + (1.2-1)*.5 + 1 + .1 + .1 + 1 + .1 + .4 + 1 + .4 + 1 - .2 + 1 - .2 + 1.1 +.5 + 2.2*.5 + .5 + .5)*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: thickWidth,
		height: .5*thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 12*delayVal + part1LastDelay
	},
	{
		x: initX + (27.7 - .7*1.6 + 3.2 - .7*1.6 + 3.2*.5 - .5 + 1 + .1 + 1 + .1 + .1 + 1 + .1 + .4 + (1.8*.5)*2 + 1.8*.5 - .5 + (1.4-1)*.5 + .5 + .25)*thickWidth,
		y: initY + (25.1 - .3 + 1 -.3 + 1 + (1.2-1)*.5 + 1 + .1 + .1 + 1 + .1 + .4 + 1 + .4 + 1 - .2 + 1 - .2 + 1.1 +.5 + 2.2*.5 + .5 + .5 + .25)*thickWidth,
		z: -thickWidth* 2.5 - plane - part2z,
		width: .5*thickWidth,
		height: .25*thickWidth,
		depth: 5 * thickWidth- depthOffest,
		animate: 2,
		duration: durationVal,
		delay: 12.5*delayVal + part1LastDelay
	},
]